In [ ]:
import os


import pandas as pd
import numpy as np
import imodmodel as imm
import starfile

In [46]:
DIR = '/Users/jantinoro/Documents/LIDo/PhD_Ferrera_Osborne/Data/Alice IMOD'
os.chdir(DIR)
mod_file = os.listdir(DIR)[1]
csv_file = os.listdir(DIR)[0]
pix_size = 8.52

In [29]:
os.listdir()

['P1_conoidMTs_forSVA_lin1.csv', 'P1_conoidMTs_forSVA_lin1.mod']

In [4]:
df = imm.read(mod_file)

In [12]:
df

      object_id  contour_id           x            y           z
0             0           0  194.962997   855.343079  204.500000
1             0           0  195.787842   854.830017  204.737503
2             0           0  196.612686   854.316956  204.975006
3             0           0  197.437531   853.803894  205.212494
4             0           0  198.262360   853.290833  205.449997
...         ...         ...         ...          ...         ...
4412          0           0  392.917389  1131.275024  149.877914
4413          0           0  393.519440  1130.792358  149.241806
4414          0           0  394.121460  1130.309692  148.605698
4415          0           0  394.723480  1129.827026  147.969589
4416          0           0  395.325500  1129.344482  147.333481

[4417 rows x 5 columns]

In [24]:
conoid_sva = pd.read_csv(csv_file)
conoid_sva

,CCC,reserved,reserved.1,pIndex,wedgeWT,NA,NA.1,NA.2,NA.3,NA.4,xOffset,yOffset,zOffset,NA.5,NA.6,reserved.2,phi,psi,theta,reserved.3
0,1.0,0,0,1,1,0,0,0,0,0,0.0,0.0,0.0,0,0,0,117.2503,-55.6477,31.2448,0
1,1.0,0,0,2,1,0,0,0,0,0,0.0,0.0,0.0,0,0,0,103.7966,-30.6102,95.1873,0
2,1.0,0,0,3,1,0,0,0,0,0,0.0,0.0,0.0,0,0,0,108.0377,-20.0801,129.9137,0
3,1.0,0,0,4,1,0,0,0,0,0,0.0,0.0,0.0,0,0,0,117.2503,-55.6477,31.2448,0
4,1.0,0,0,5,1,0,0,0,0,0,0.0,0.0,0.0,0,0,0,-111.3746,164.6530,40.6653,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4412,1.0,0,0,4413,1,0,0,0,0,0,0.0,0.0,0.0,0,0,0,-43.4874,114.3954,61.2535,0
4413,1.0,0,0,4414,1,0,0,0,0,0,0.0,0.0,0.0,0,0,0,45.3087,-61.5957,115.2467,0
4414,1.0,0,0,4415,1,0,0,0,0,0,0.0,0.0,0.0,0,0,0,50.2596,-33.9683,84.2638,0
4415,1.0,0,0,4416,1,0,0,0,0,0,0.0,0.0,0.0,0,0,0,18.0212,27.6442,41.9841,0
4416,1.0,0,0,4417,1,0,0,0,0,0,0.0,0.0,0.0,0,0,0,-50.1826,135.8139,83.4072,0

In [30]:
conoid_sva['CCC'].value_counts()

CCC
1.0    4417
Name: count, dtype: int64

In [ ]:
angles = conoid_sva[['phi', 'psi', 'theta']]
coords = df[['x', 'y', 'z']]

pandas.DataFrame

In [ ]:
PATTERN = re.compile(
    r"^Position_(?P<pos>\d+)(?:_(?P<sub>\d+))?$",
    re.IGNORECASE,
)


  files = [f for f in directory.glob("[Pp]osition_*") if PATTERN.match(f.stem)]

In [37]:
combined_df = pd.concat([coords, angles], axis=1)

In [56]:
combined_df

,rlnCoordinateX,rlnCoordinateY,rlnCoordinateZ,rlnAngleRot,rlnAngleTilt,rlnAnglePsi,rlnMicrographName,rlnImagePixelSize,rlnOriginX,rlnOriginY,rlnOriginZ
0,194.962997,855.343079,204.500000,117.2503,-55.6477,31.2448,/d/emr222/u/abrin43/perkinsus/bi34130-42/warp/...,8.52,0.0,0.0,0.0
1,195.787842,854.830017,204.737503,103.7966,-30.6102,95.1873,/d/emr222/u/abrin43/perkinsus/bi34130-42/warp/...,8.52,0.0,0.0,0.0
2,196.612686,854.316956,204.975006,108.0377,-20.0801,129.9137,/d/emr222/u/abrin43/perkinsus/bi34130-42/warp/...,8.52,0.0,0.0,0.0
3,197.437531,853.803894,205.212494,117.2503,-55.6477,31.2448,/d/emr222/u/abrin43/perkinsus/bi34130-42/warp/...,8.52,0.0,0.0,0.0
4,198.262360,853.290833,205.449997,-111.3746,164.6530,40.6653,/d/emr222/u/abrin43/perkinsus/bi34130-42/warp/...,8.52,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
4412,392.917389,1131.275024,149.877914,-43.4874,114.3954,61.2535,/d/emr222/u/abrin43/perkinsus/bi34130-42/warp/...,8.52,0.0,0.0,0.0
4413,393.519440,1130.792358,149.241806,45.3087,-61.5957,115.2467,/d/emr222/u/abrin43/perkinsus/bi34130-42/warp/...,8.52,0.0,0.0,0.0
4414,394.121460,1130.309692,148.605698,50.2596,-33.9683,84.2638,/d/emr222/u/abrin43/perkinsus/bi34130-42/warp/...,8.52,0.0,0.0,0.0
4415,394.723480,1129.827026,147.969589,18.0212,27.6442,41.9841,/d/emr222/u/abrin43/perkinsus/bi34130-42/warp/...,8.52,0.0,0.0,0.0
4416,395.325500,1129.344482,147.333481,-50.1826,135.8139,83.4072,/d/emr222/u/abrin43/perkinsus/bi34130-42/warp/...,8.52,0.0,0.0,0.0

# Additional information needed for the complete star file

- We have all three euler angles
- we have the coords 
- Need the micrograph name, i.e., the reconstruction in which this came from -> This is the tomostar
- and maybe the origin? 
- pixel size? - 8.52A per pix

In [44]:
combined_df.rename(columns={'x': 'rlnCoordinateX', 'y': 'rlnCoordinateY', 'z': 'rlnCoordinateZ', 'phi': 'rlnAngleRot', 'psi': 'rlnAngleTilt', 'theta': 'rlnAnglePsi'}, inplace=True)

In [58]:
# file path to tomostar file in which these csv and mod file came from
# /d/emr222/u/abrin43/perkinsus/bi34130-42/warp/tomostar/Position_1.tomostar
combined_df['rlnMicrographName'] = 'Position_1.tomostar'
combined_df['rlnImagePixelSize'] = pix_size
combined_df[['rlnOriginX', 'rlnOriginY', 'rlnOriginZ']] = 0.0

In [50]:
os.getcwd()

'/Users/jantinoro/Documents/LIDo/PhD_Ferrera_Osborne/Data/Alice IMOD'

In [59]:
test_star = starfile.write(combined_df, '/Users/jantinoro/Documents/Coding_projects/python_projects/imod2relion/test_relative.star', overwrite=True)